CONFIG_FILE_NAME = 'config.txt'
MSG_WITH_SERVER = 'Hello'
MAX_RECV = 1024
USERNAME = 'user1'
PASSWORD = '1234'
USER_MAIL = 'user1@gmail.com'

CODE_INDEX = 0
LENGTH_INDEX = 1
MESSAGE_INDEX = 5

INT_BYTES = 4

LOGIN_CODE = '\x19'.encode()
SIGN_UP_CODE = 'I'.encode()
